server:
  port: 9090

spring:
  application:
    name: erp-gateway
  cloud:
    nacos:
      discovery:
        enabled: ${NACOS_DISCOVERY_ENABLED:true}
        register-enabled: ${NACOS_DISCOVERY_ENABLED:true}
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: erp-system-login
          uri: lb://erp-system
          predicates:
            - Path=/login
        - id: erp-auth
          uri: lb://erp-auth
          predicates:
            - Path=/auth/**
        - id: erp-system
          uri: lb://erp-system
          predicates:
            - Path=/system/**
