module.name=erp-auth
module.application-class=com.erp.auth.AuthApplication
module.config-location=classpath:/bootstrap/erp-auth.yml
module.web-application-type=SERVLET
module.server-port=9091
module.order=10
module.enabled=true
