-- 20260322_00: workflow 基础表兜底自举，保证独立服务在缺表场景下可启动并返回空列表而不是 500

CREATE TABLE IF NOT EXISTS `sys_todo_task` (
  `todo_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '待办ID',
  `instance_id` bigint(20) DEFAULT NULL COMMENT '流程实例ID',
  `task_id` bigint(20) DEFAULT NULL COMMENT '流程任务ID',
  `tenant_id` varchar(20) NOT NULL COMMENT '租户编号',
  `process_name` varchar(100) NOT NULL COMMENT '流程名称',
  `node_name` varchar(100) DEFAULT NULL COMMENT '当前节点',
  `business_no` varchar(64) DEFAULT NULL COMMENT '业务单号',
  `priority` char(1) DEFAULT 'M' COMMENT '优先级（H高 M中 L低）',
  `status` char(1) DEFAULT '0' COMMENT '状态（0待处理 1处理中 2已完成）',
  `assignee_user_id` bigint(20) NOT NULL COMMENT '办理人用户ID',
  `due_time` datetime DEFAULT NULL COMMENT '截止时间',
  `claim_time` datetime DEFAULT NULL COMMENT '签收时间',
  `finish_time` datetime DEFAULT NULL COMMENT '办结时间',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`todo_id`),
  KEY `idx_todo_assignee` (`tenant_id`, `assignee_user_id`, `status`),
  KEY `idx_todo_workflow` (`tenant_id`, `instance_id`, `task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程待办任务表';

CREATE TABLE IF NOT EXISTS `sys_wf_definition` (
  `definition_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '流程定义ID',
  `tenant_id` varchar(20) NOT NULL COMMENT '租户编号',
  `process_key` varchar(64) NOT NULL COMMENT '流程标识',
  `process_name` varchar(128) NOT NULL COMMENT '流程名称',
  `category` varchar(64) DEFAULT 'custom' COMMENT '流程分类',
  `version` int(11) NOT NULL DEFAULT 1 COMMENT '版本号',
  `status` char(1) DEFAULT '0' COMMENT '状态（0草稿 1已发布 2停用）',
  `published_slot` tinyint(1) GENERATED ALWAYS AS (CASE WHEN `status` = '1' THEN 1 ELSE NULL END) STORED COMMENT '已发布唯一槽位',
  `form_schema` longtext COMMENT '表单结构JSON',
  `model_content` longtext COMMENT '流程设计JSON',
  `publish_by` varchar(64) DEFAULT NULL COMMENT '发布人',
  `publish_time` datetime DEFAULT NULL COMMENT '发布时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`definition_id`),
  UNIQUE KEY `idx_wf_def_key_ver` (`tenant_id`, `process_key`, `version`),
  UNIQUE KEY `uk_wf_def_publish_slot` (`tenant_id`, `process_key`, `published_slot`),
  KEY `idx_wf_def_status` (`tenant_id`, `status`, `category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程定义表';

CREATE TABLE IF NOT EXISTS `sys_wf_business_binding` (
  `binding_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '绑定ID',
  `tenant_id` varchar(20) NOT NULL COMMENT '租户编号',
  `domain_type` varchar(64) NOT NULL COMMENT '业务域类型',
  `action_code` varchar(32) NOT NULL COMMENT '业务动作编码',
  `process_key` varchar(64) NOT NULL COMMENT '流程标识',
  `is_default` char(1) DEFAULT '0' COMMENT '是否默认（0否 1是）',
  `status` char(1) DEFAULT '0' COMMENT '状态（0启用 1停用）',
  `priority` int(11) DEFAULT 100 COMMENT '优先级，数值越小越优先',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`binding_id`),
  UNIQUE KEY `uk_wf_business_binding` (`tenant_id`, `domain_type`, `action_code`, `process_key`),
  KEY `idx_wf_business_action` (`tenant_id`, `domain_type`, `action_code`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程业务动作绑定表';

CREATE TABLE IF NOT EXISTS `sys_wf_instance` (
  `instance_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '流程实例ID',
  `tenant_id` varchar(20) NOT NULL COMMENT '租户编号',
  `definition_id` bigint(20) NOT NULL COMMENT '流程定义ID',
  `definition_version` int(11) DEFAULT NULL COMMENT '发起时流程定义版本号',
  `process_key` varchar(64) NOT NULL COMMENT '流程标识',
  `process_name` varchar(128) NOT NULL COMMENT '流程名称',
  `category` varchar(64) DEFAULT 'custom' COMMENT '流程分类',
  `owner_service` varchar(32) DEFAULT NULL COMMENT '所属业务服务',
  `business_no` varchar(64) NOT NULL COMMENT '业务单号',
  `business_type` varchar(64) DEFAULT NULL COMMENT '业务类型',
  `domain_type` varchar(64) DEFAULT NULL COMMENT '业务域类型',
  `action_code` varchar(32) DEFAULT NULL COMMENT '业务动作编码',
  `idempotency_key` varchar(128) DEFAULT NULL COMMENT '幂等键',
  `form_data` longtext COMMENT '表单数据JSON',
  `form_schema_snapshot` longtext COMMENT '发起时表单结构快照JSON',
  `model_content_snapshot` longtext COMMENT '发起时流程模型快照JSON',
  `current_node` varchar(128) DEFAULT NULL COMMENT '当前节点',
  `initiator_user_id` bigint(20) NOT NULL COMMENT '发起人用户ID',
  `initiator_user_name` varchar(64) DEFAULT NULL COMMENT '发起人账号',
  `initiator_nick_name` varchar(64) DEFAULT NULL COMMENT '发起人昵称',
  `status` char(1) DEFAULT '0' COMMENT '状态（0进行中 1已完成 2已驳回 3已撤销）',
  `start_time` datetime DEFAULT NULL COMMENT '发起时间',
  `finish_time` datetime DEFAULT NULL COMMENT '结束时间',
  `last_action` varchar(32) DEFAULT NULL COMMENT '最近动作',
  `last_action_user_id` bigint(20) DEFAULT NULL COMMENT '最近动作人ID',
  `last_action_user_name` varchar(64) DEFAULT NULL COMMENT '最近动作人账号',
  `last_action_time` datetime DEFAULT NULL COMMENT '最近动作时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`instance_id`),
  KEY `idx_wf_inst_status` (`tenant_id`, `status`, `start_time`),
  KEY `idx_wf_inst_business` (`tenant_id`, `business_no`),
  KEY `idx_wf_inst_business_status` (`tenant_id`, `business_type`, `business_no`, `status`),
  KEY `idx_wf_inst_idempotency` (`tenant_id`, `idempotency_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程实例表';

CREATE TABLE IF NOT EXISTS `sys_wf_task` (
  `task_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '流程任务ID',
  `tenant_id` varchar(20) NOT NULL COMMENT '租户编号',
  `instance_id` bigint(20) NOT NULL COMMENT '流程实例ID',
  `definition_id` bigint(20) NOT NULL COMMENT '流程定义ID',
  `node_key` varchar(64) DEFAULT NULL COMMENT '节点编码',
  `node_name` varchar(128) DEFAULT NULL COMMENT '节点名称',
  `candidate_user_ids` varchar(500) DEFAULT NULL COMMENT '候选办理人ID列表',
  `assignee_user_id` bigint(20) DEFAULT NULL COMMENT '办理人用户ID',
  `assignee_user_name` varchar(64) DEFAULT NULL COMMENT '办理人账号',
  `assignee_nick_name` varchar(64) DEFAULT NULL COMMENT '办理人昵称',
  `status` char(1) DEFAULT '0' COMMENT '状态（0待处理 1处理中 2已同意 3已驳回 4已转交 5已取消）',
  `action_comment` varchar(500) DEFAULT NULL COMMENT '审批意见',
  `todo_id` bigint(20) DEFAULT NULL COMMENT '关联待办ID',
  `due_time` datetime DEFAULT NULL COMMENT '截止时间',
  `claim_time` datetime DEFAULT NULL COMMENT '签收时间',
  `finish_time` datetime DEFAULT NULL COMMENT '办结时间',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`task_id`),
  KEY `idx_wf_task_assignee` (`tenant_id`, `assignee_user_id`, `status`),
  KEY `idx_wf_task_instance` (`tenant_id`, `instance_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程任务表';

CREATE TABLE IF NOT EXISTS `sys_wf_task_action` (
  `action_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '动作记录ID',
  `tenant_id` varchar(20) NOT NULL COMMENT '租户编号',
  `instance_id` bigint(20) NOT NULL COMMENT '流程实例ID',
  `task_id` bigint(20) DEFAULT NULL COMMENT '流程任务ID',
  `definition_id` bigint(20) DEFAULT NULL COMMENT '流程定义ID',
  `node_name` varchar(128) DEFAULT NULL COMMENT '节点名称',
  `action_type` varchar(32) NOT NULL COMMENT '动作类型',
  `action_user_id` bigint(20) DEFAULT NULL COMMENT '动作人用户ID',
  `action_user_name` varchar(64) DEFAULT NULL COMMENT '动作人账号',
  `action_nick_name` varchar(64) DEFAULT NULL COMMENT '动作人昵称',
  `from_assignee_user_id` bigint(20) DEFAULT NULL COMMENT '来源办理人ID',
  `to_assignee_user_id` bigint(20) DEFAULT NULL COMMENT '目标办理人ID',
  `action_comment` varchar(500) DEFAULT NULL COMMENT '动作意见',
  `action_time` datetime DEFAULT NULL COMMENT '动作时间',
  PRIMARY KEY (`action_id`),
  KEY `idx_wf_action_instance` (`tenant_id`, `instance_id`, `action_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程任务动作记录表';
