module.name=erp-system
module.application-class=com.erp.system.SystemModuleApplication
module.config-location=classpath:/bootstrap/erp-system.yml
module.web-application-type=SERVLET
module.server-port=9092
module.order=20
module.enabled=true
