module.name=erp-gateway
module.application-class=com.erp.gateway.GatewayApplication
module.config-location=classpath:/bootstrap/erp-gateway.yml
module.web-application-type=REACTIVE
module.order=30
module.enabled=true
