server:
  port: 9090

spring:
  application:
    name: erp-gateway
  config:
    import:
      - optional:classpath:/bootstrap/erp-gateway.yml
      - optional:nacos:erp-gateway.yml?refreshable=true
  cloud:
    nacos:
      discovery:
        enabled: ${NACOS_DISCOVERY_ENABLED:true}
        register-enabled: ${NACOS_DISCOVERY_ENABLED:true}
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
