module.name=erp-business
module.application-class=com.erp.business.BusinessApplication
module.config-location=classpath:/bootstrap/erp-business.yml
module.web-application-type=SERVLET
module.server-port=9093
module.order=25
module.enabled=true
